-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- 1. PRODUCTS TABLE
create table public.products (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  description text,
  price numeric not null,
  category text not null,
  image_url text,
  stock integer default 0,
  min_stock integer default 5,
  barcode text unique,
  unit_type text default 'unit' check (unit_type in ('unit', 'kg'))
);

-- 2. COURIERS TABLE
create table public.couriers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  active boolean default true
);

-- 3. DELIVERY ZONES TABLE
create table public.delivery_zones (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null
);

-- 4. ORDERS TABLE
create table public.orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  display_id text, -- stores the #123 format
  status text default 'Pendente',
  customer_name text,
  customer_phone text,
  customer_address text, -- JSON or text
  payment_method text,
  total numeric not null,
  delivery_fee numeric default 0,
  delivery_zone text,
  courier_id bigint references public.couriers(id),
  cancellation_reason text
);

-- 5. ORDER ITEMS TABLE
create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade not null,
  product_id bigint references public.products(id),
  product_name text, -- snapshot in case product is deleted
  quantity numeric not null,
  unit_price numeric not null,
  note text
);

-- 6. INVENTORY LOGS TABLE
create table public.inventory_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  product_id bigint references public.products(id) on delete cascade not null,
  change_amount numeric not null,
  type text not null check (type in ('sale', 'manual_adjustment', 'restock')),
  reason text
);

-- 6. STORE SETTINGS TABLE (Single Row)
create table public.store_settings (
  id bigint generated by default as identity primary key,
  description text,
  phone text,
  instagram text,
  address text,
  weekday_hours text,
  weekend_hours text
);

-- Insert default settings
insert into public.store_settings (description, phone, instagram, address, weekday_hours, weekend_hours)
values (
  'O verdadeiro sabor do churrasco na sua mesa.',
  '(11) 99999-9999',
  '@casadosassados',
  'Av. Principal, 123 - Centro',
  '11h às 15h / 18h às 23h',
  '11h às 23h'
);

-- --- SECURITY (RLS) ---
alter table public.products enable row level security;
alter table public.couriers enable row level security;
alter table public.delivery_zones enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.store_settings enable row level security;

-- POLICIES

-- Products: Everyone can view, only Admin (Auth) can edit
create policy "Public Products View" on public.products for select using (true);
create policy "Admin Products Edit" on public.products for all using (auth.role() = 'authenticated');

-- Couriers: Only Admin view/edit
create policy "Admin Couriers" on public.couriers for all using (auth.role() = 'authenticated');

-- Delivery Zones: Public view, Admin edit
create policy "Public Zones View" on public.delivery_zones for select using (true);
create policy "Admin Zones Edit" on public.delivery_zones for all using (auth.role() = 'authenticated');

-- Orders: Public can INSERT (Checkout). Only Admin can SELECT/UPDATE (Dashboard).
-- Ideally, customers should read their own orders via ID/Cookie logic, but for now assuming public cannot list all orders.
create policy "Public Create Order" on public.orders for insert with check (true); 
create policy "Admin Manage Orders" on public.orders for all using (auth.role() = 'authenticated');

-- Order Items: Same as orders
create policy "Public Create Order Items" on public.order_items for insert with check (true);
create policy "Admin Manage Order Items" on public.order_items for all using (auth.role() = 'authenticated');

-- Settings: Public view, Admin edit
create policy "Public Settings View" on public.store_settings for select using (true);
create policy "Admin Settings Edit" on public.store_settings for all using (auth.role() = 'authenticated');
